#!/bin/bash
chmod 777 buildscript
./buildscript
echo "Running A1 tests"
for filename in test/a1/*; do 
  printf "Test $filename _________________________________\n"
  ./joosc $filename
  printf "\n\n"
done
