#!/bin/bash
chmod 777 buildscript
./buildscript

javafiles=""
for f in $(find test/java3 -name '*.java'); do
  chmod 777 $f
  javafiles="$javafiles $f";
done

failuresArray=

echo "Running A3 tests J1_*"
for filename in test/a3/J1_*.java; do 
  printf "Test $filename\n"
  testname="$filename"
  filename="$filename $javafiles"
  ./joosc $filename
  if [ $? == 42 ]
    then
    failuresArray+=($testname)
  fi
done

for filename in test/a3/Je_*.java; do 
  printf "Test $filename\n"
  testname="$filename"
  filename="$filename $javafiles"
  ./joosc $filename
  if [ $? == 0 ]
    then
    failuresArray+=($testname)
  fi
done

for directory in test/a3/J1_*/; do 
  printf "Test $directory\n"
  testname="$directory"
  params=""
  for f in $(find $directory -name '*.java'); do
    chmod 777 $f
    params="$params $f";
  done
  params="$params $javafiles"
  ./joosc $params
  if [ $? == 42 ]
    then
    failuresArray+=($testname)
  fi
  printf "\n\n"
done

for directory in test/a3/Je_*/; do 
  printf "Test $directory\n"
  testname="$directory"
  params=""
  for f in $(find $directory -name '*.java'); do
    chmod 777 $f
    params="$params $f";
  done
  params="$params $javafiles"
  ./joosc $params
  if [ $? == 0 ]
    then
    failuresArray+=($testname)
  fi
  printf "\n\n"
done

echo "++++++++++++Test Failures++++++++++++"
printf '%s\n' "${failuresArray[@]}"